@echo off
REM Import all batch files in order
cd /d "%~dp0"

echo Importing 01_base_inventory.sql...
mysql -u root -p cabadbaran_agriculture < "01_base_inventory.sql"

echo Importing 02_users_batch_01.sql...
mysql -u root -p cabadbaran_agriculture < "02_users_batch_01.sql"

echo Importing 02_users_batch_02.sql...
mysql -u root -p cabadbaran_agriculture < "02_users_batch_02.sql"

echo Importing 02_users_batch_03.sql...
mysql -u root -p cabadbaran_agriculture < "02_users_batch_03.sql"

echo Importing 02_users_batch_04.sql...
mysql -u root -p cabadbaran_agriculture < "02_users_batch_04.sql"

echo Importing 02_users_batch_05.sql...
mysql -u root -p cabadbaran_agriculture < "02_users_batch_05.sql"

echo Importing 03_borrows_batch_01.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_01.sql"

echo Importing 03_borrows_batch_02.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_02.sql"

echo Importing 03_borrows_batch_03.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_03.sql"

echo Importing 03_borrows_batch_04.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_04.sql"

echo Importing 03_borrows_batch_05.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_05.sql"

echo Importing 03_borrows_batch_06.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_06.sql"

echo Importing 03_borrows_batch_07.sql...
mysql -u root -p cabadbaran_agriculture < "03_borrows_batch_07.sql"

echo Importing 04_payments_batch_01.sql...
mysql -u root -p cabadbaran_agriculture < "04_payments_batch_01.sql"

echo Importing 04_payments_batch_02.sql...
mysql -u root -p cabadbaran_agriculture < "04_payments_batch_02.sql"

echo Importing 05_login_attempts_batch_01.sql...
mysql -u root -p cabadbaran_agriculture < "05_login_attempts_batch_01.sql"

echo Importing 05_login_attempts_batch_02.sql...
mysql -u root -p cabadbaran_agriculture < "05_login_attempts_batch_02.sql"

echo Importing 06_activity_log_batch_01.sql...
mysql -u root -p cabadbaran_agriculture < "06_activity_log_batch_01.sql"

echo Importing 06_activity_log_batch_02.sql...
mysql -u root -p cabadbaran_agriculture < "06_activity_log_batch_02.sql"

echo Importing 06_activity_log_batch_03.sql...
mysql -u root -p cabadbaran_agriculture < "06_activity_log_batch_03.sql"

